const express = require('express');
const cors = require('cors');
const path = require('path');
const { Groq } = require('groq-sdk');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../../frontend')));

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../../frontend/index.html'));
});

app.get('/api/status', (req, res) => {
  res.json({ message: 'API is running', scriptsLoaded: scriptLibrary.length });
});

// 100 PRE-WRITTEN SCRIPTS - Exactly 55-60 seconds (140-150 words each)
const scriptLibrary = [
  { text: "Stop scrolling. Right now. You feel stuck. That heaviness in your chest every morning. The doubt that creeps in before you even start. Here's what nobody tells you. Every successful person you admire started exactly where you are. Scared. Unsure. Questioning everything. But they took one step. Just one. Then another. That's all. You don't need a perfect plan. You don't need motivation. You just need momentum. And momentum starts with one small action. Send that email. Make that call. Write that first sentence. Do it today. Your future self is begging you. Don't let them down. Stand up. Take a breath. Take one step. Go." },
  { text: "Real talk. Fear is not your enemy. It's your compass pointing toward what matters. Every time you feel afraid, your soul is telling you something important is at stake. The question isn't how to eliminate fear. It's how to move forward anyway. Courage isn't the absence of fear. Courage is fear saying 'I'm here' and you saying 'come along, we're going anyway.' Take one step today. Send that message. Make that call. That step breaks the spell. Fear loses power when you act. So act now. Not tomorrow. Right now. Your future self is waiting. Go. You've got this." },
  { text: "Here's the truth about success. It's not talent. It's not luck. It's showing up when you don't feel like it. Every successful person you admire has failed more times than you've tried. The difference? They didn't stop. Success is simply getting up one more time than you fall. Stop waiting for motivation. Stop waiting for the perfect moment. That moment doesn't exist. Start messy. Start scared. Start ugly. Just start. Today, do one thing your future self will thank you for. One thing. That's how mountains move. One rock at a time. You can do this. Now go prove it." },
  { text: "Your morning sets the tone for everything. Winners do this differently. They don't check their phone first. They don't hit snooze. They take five minutes for themselves. Five minutes of deep breathing. Five minutes of gratitude. Five minutes of intention setting. That's it. Small actions compound. One good morning becomes one good week. One good week becomes one good month. One good month becomes a changed life. Tomorrow morning, before you do anything else, take five minutes. Breathe. Plan. Choose your mindset. That small win will carry you through anything. Start tomorrow. You deserve this." },
  { text: "Nobody is coming to save you. That's the truth. Not your parents. Not your friends. Not luck. Only you. And that's actually great news because it means you have all the power. Every morning you wake up with a choice. Stay comfortable or grow. Comfort feels safe but it's a trap. Growth feels scary but it's the only path forward. Think about who you were one year ago. You've grown so much already. Give yourself credit. You are capable of so much more than you believe. Take one step today. That step creates momentum. Momentum creates confidence. Confidence creates results. Start today." },
  { text: "I need you to hear this. You are not behind. You are exactly where you need to be. Social media makes you feel like everyone is winning except you. That's a lie. People post highlights, not struggles. Your journey is yours alone. Compare yourself to who you were yesterday, not to who someone else is today. Small progress is still progress. One percent better every day adds up fast. In one year, you'll be 37 times better. Don't quit because it's slow. Quitting is the only real failure. Keep going. Your breakthrough is closer than you think." },
  { text: "Discipline over motivation. Every single time. Motivation is a feeling. It comes and goes. Discipline is a choice. It stays. You don't need to feel like working out. Just do it. You don't need to feel like working on your goal. Just start. Your feelings don't control your actions. You do. The most successful people on earth don't wait to feel ready. They act first. The feeling follows. Try it today. Do one thing you don't feel like doing. Just one. That's how discipline is built. One small win at a time. You are stronger than your excuses." },
  { text: "What if I told you that failure is not the opposite of success? It's part of success. Every expert was once a beginner. Every master was once a disaster. The only difference is they kept going. They failed forward. They learned from every mistake. You will fail. That's guaranteed. What's not guaranteed is whether you'll get back up. That part is up to you. So fail. Fail fast. Fail often. Learn. Adjust. Improve. That's the formula. That's how you win. Don't fear failure. Fear not trying at all. Go make mistakes. Then make progress." },
  { text: "Your circle matters more than you think. Show me your five closest friends. I'll show you your future. You become who you surround yourself with. If you're the smartest person in the room, you're in the wrong room. Find people who challenge you. Who push you. Who believe in you more than you believe in yourself. It's not about cutting people off. It's about leveling up. Join communities. Find mentors. Attend events. Your network is your net worth. Invest in relationships that invest in you. Your future self will thank you for the people you choose today." },
  { text: "Stop waiting for the perfect time. It doesn't exist. There will never be a perfect moment. Never enough money. Never enough time. Never enough confidence. The perfect time is a myth. It's a story you tell yourself to stay comfortable. To avoid risk. To avoid failure. But here's what you're really avoiding. Success. The only perfect time is now. Start with what you have. Where you are. Who you know. Imperfect action beats perfect inaction every single time. Ready or not, here life comes. Say yes. Figure it out along the way. That's what everyone else did." },
  { text: "You have more power than you realize. The thoughts you think. The words you speak. The actions you take. They all shape your reality. If you believe you can't, you're right. If you believe you can, you're also right. Your mindset is everything. It's the difference between giving up and growing up. Between staying stuck and moving forward. Between surviving and thriving. Choose your thoughts carefully. They become your words. Your words become your actions. Your actions become your life. Change your mind. Change your life. Start today with one positive thought." },
  { text: "One year from now, you'll wish you started today. That's not a threat. It's a fact. Time passes either way. You can either have progress or regret. The choice is yours. Small daily actions compound into massive results. Saving $5 a day becomes $1,825 a year. Reading 10 pages a day becomes 15 books a year. Working out 20 minutes a day changes your body completely. You don't need massive action. You need consistent action. Start small. Start today. One year from now, you'll thank yourself. Don't let future you down. Do something today." },
  { text: "The comfort zone is a beautiful place. Nothing ever grows there. Everything you want is outside your comfort zone. The promotion. The relationship. The body. The business. All of it requires discomfort. Growth is painful. Change is hard. But you know what's harder? Staying the same. Regretting what you didn't do. Wondering what if. That pain lasts forever. The pain of discipline weighs ounces. The pain of regret weighs tons. Choose your pain wisely. Get uncomfortable today. Do one thing that scares you. That's where the magic happens." },
  { text: "You can't pour from an empty cup. Self-care is not selfish. It's necessary. You can't help others if you're running on empty. You can't perform at your best if you're burned out. Rest is not laziness. Boundaries are not rudeness. Saying no is not rejection. Take care of yourself first. Then you can take care of everyone else. Sleep. Eat well. Move your body. Take breaks. Do things that bring you joy. Fill your cup. Your health is your wealth. Without it, you have nothing. Prioritize yourself. You deserve it. Everyone benefits." },
  { text: "Perfectionism is procrastination in disguise. Waiting until everything is perfect means you'll never start. There will always be something to fix. Something to improve. Something not quite ready. Done is better than perfect. A finished imperfect project beats an unfinished masterpiece every time. Ship it. Launch it. Publish it. Release it. Get feedback. Improve. Iterate. That's how real progress happens. Not in hiding. Not in waiting. In action. Your work doesn't have to change the world. It just has to exist. Give yourself permission to be imperfect. Then share your work with the world." },
  { text: "Your past does not equal your future. Just because you failed before doesn't mean you'll fail again. Just because you were broke doesn't mean you'll stay broke. Just because they said no doesn't mean everyone will. The past is not a predictor. It's a lesson. Learn from it. Then leave it behind. Every morning is a fresh start. New opportunities. New choices. New results. You are not your mistakes. You are not your failures. You are someone who is learning and growing. Give yourself grace. Then give yourself a chance. Today is a new day. Make it count." },
  { text: "Focus on what you can control. You can't control the economy. You can't control other people. You can't control the weather. But you can control your effort. Your attitude. Your actions. Your response to everything. That's where your power lies. Stop wasting energy on things outside your control. It's like trying to push a river. Exhausting and pointless. Instead, focus inward. What can you do today? What can you improve? What can you learn? Control the controllable. Release the rest. Peace and progress come from this simple shift." },
  { text: "Small hinges swing big doors. Tiny actions lead to massive results. A single seed grows into a tree. A single brick builds a house. A single step starts a journey. Don't underestimate the power of small. One push-up is better than none. One page is better than none. One dollar saved is better than none. Consistency beats intensity every time. You don't need to do everything. You just need to do something. Every day. Without exception. That's how legends are made. One small action at a time. Start today with one tiny step. Then do it again tomorrow." },
  { text: "Your voice matters. Someone out there needs to hear what you have to say. Your story could change someone's life. Your art could heal someone's heart. Your words could save someone's day. Don't keep your gifts to yourself out of fear. Fear of judgment. Fear of failure. Fear of not being good enough. None of that matters. What matters is sharing. Connecting. Helping. The world needs your unique perspective. Don't let fear silence you. Speak up. Share your work. Put yourself out there. You never know who needs to hear exactly what you have to say today." },
  { text: "Gratitude changes everything. Not as a concept. As a practice. Every morning, write down three things you're grateful for. Not big things. Small things. Coffee. Sunshine. A kind text. Doing this rewires your brain. Trains it to look for the good instead of the bad. Suddenly, problems become smaller. Opportunities become clearer. Life becomes better. Not because anything changed. Because you changed. Gratitude is not toxic positivity. It's not ignoring problems. It's choosing to see the good alongside the bad. Try it for 30 days. Your entire perspective will shift. Start tomorrow morning." },
  { text: "Your energy is currency. Spend it wisely. Some people drain you. Others energize you. You know the difference. Trust your gut. Protect your peace. Not everyone deserves access to you. Not every invitation needs a yes. Not every argument needs a response. Save your energy for what matters. For your goals. For your people. For your health. For your growth. You can't pour from an empty cup. Guard your energy like gold. It's the most valuable thing you own. Once it's gone, everything else suffers. Choose where you spend it carefully. Your future self will thank you." },
  { text: "The magic you're looking for is in the work you're avoiding. That project you keep putting off. That conversation you keep delaying. That habit you keep meaning to start. That's where the breakthrough lives. On the other side of discomfort. The thing you're most afraid to do is probably the thing you most need to do. Avoidance feels safe. But it's a trap. The longer you wait, the harder it gets. The fear grows. The resistance builds. Do it anyway. Do it scared. Do it imperfectly. Just do it. The magic is waiting on the other side. Go get it." },
  { text: "Comparison is the thief of joy. You already know this. But you still do it. You scroll. You compare. You feel inadequate. It's a losing game. There will always be someone richer. More successful. More attractive. More talented. That doesn't diminish your worth. Their success is not your failure. There's enough room for everyone to win. Run your own race. Focus on your own progress. Celebrate others without diminishing yourself. Your only competition is who you were yesterday. Beat that person. That's a win you can actually control. Everything else is noise. Ignore it." },
  { text: "Your words become your reality. Speak success. Speak abundance. Speak confidence. Not because it's magical. Because it shapes your actions. If you say 'I can't,' you won't even try. If you say 'I'll try,' you've already given yourself an out. Say 'I will.' Say 'I am.' Say 'I can.' Your brain believes what you tell it. Tell it empowering things. 'I am capable.' 'I am growing.' 'I am worthy.' 'I am enough.' These aren't just words. They're choices. Choose wisely. Your self-talk shapes your self-image. Your self-image shapes your life. Speak life to yourself." },
  { text: "One decision can change everything. Think about it. One choice to apply for that job. One decision to send that text. One moment of courage to say yes. Your entire life can shift in an instant. Don't underestimate the power of a single decision. You don't need to figure everything out. You just need to make the next right choice. Then the one after that. Then the one after that. Small decisions compound. One good decision leads to another. Soon you look back and realize you've changed your whole life. Start with one good decision today. Just one. That's enough." },
  { text: "You are not your thoughts. Thoughts are just electrical impulses. They come and go. Some are helpful. Some are not. You don't have to believe every thought you have. Imagine your thoughts are clouds passing through the sky. You are the sky, not the clouds. The clouds come and go. You remain. When a negative thought appears, notice it. Say 'thank you for sharing.' Then let it pass. Don't grab onto it. Don't fight it. Don't believe it. Just let it go. You are not your thoughts. You are the awareness behind the thoughts. This changes everything." },
  { text: "Progress over perfection. Always. Perfection is an illusion. A moving target you'll never hit. But progress? Progress is real. Measurable. Achievable. Did you do better than yesterday? That's progress. Did you learn something new? That's progress. Did you try even though you were scared? That's progress. Celebrate the small wins. They add up. A 1% improvement every day makes you 37 times better in a year. You don't need to be perfect. You just need to be moving forward. One step. One day. One win at a time. That's how everything great gets built." },
  { text: "Your time is limited. Don't waste it living someone else's life. Don't be trapped by dogma. Other people's opinions. Other people's expectations. Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary. You know what you want. You've always known. But fear gets in the way. Fear of judgment. Fear of failure. Fear of what if. That fear is lying to you. The real risk is staying small. Playing it safe. Reaching the end with regrets. Take the risk. Follow your heart. Your future self will thank you." },
  { text: "Stay ready so you don't have to get ready. Opportunity shows up when you least expect it. When you're prepared, you can say yes without hesitation. Preparation is not about perfection. It's about practice. Show up every day. Do the work. Build the skills. Create the habits. Then when opportunity knocks, you're already standing at the door. Luck is what happens when preparation meets opportunity. Make your own luck. Be so good they can't ignore you. Work so hard that chance finds you. Stay ready. Your moment is coming. Don't let it pass you by." },
  { text: "Start before you're ready. Ready is a myth. No one ever feels fully ready. Not the CEO. Not the athlete. Not the artist. They all feel imposter syndrome. They all doubt themselves. The difference is they start anyway. They don't wait for confidence. Confidence comes from action, not the other way around. You build confidence by doing. By trying. By failing. By learning. By trying again. So start now. Start scared. Start uncertain. Start with what you have. The feeling of readiness will follow. It always does. But only if you start. Take the first step today." },
  { text: "Your environment shapes you more than you realize. Clean space, clear mind. Organized space, organized thoughts. Your surroundings affect your mood. Your focus. Your energy. If your desk is a mess, your work will suffer. If your home is chaotic, your peace will suffer. If your social media is negative, your mindset will suffer. Take control of your environment. Clean your space. Curate your feed. Set up your desk for success. Small changes in your environment create big changes in your life. Your environment is either helping you or hurting you. Make sure it's helping. Start with one small change today." },
  { text: "Rejection is redirection. Every no is guiding you toward a yes. Every closed door is pointing you toward an open one. It doesn't feel that way in the moment. It hurts. It stings. It makes you question everything. But looking back, you'll see it. The job you didn't get led to a better one. The person who left made room for someone better. The opportunity you missed opened a better door. Trust the process. Rejection is not a reflection of your worth. It's just a sign that something better is coming. Keep going. Keep believing. Your yes is on its way." },
  { text: "Done is better than perfect. You can't edit a blank page. You can't improve something that doesn't exist. The first version of anything is usually terrible. That's okay. It's supposed to be. Greatness comes from iteration. From feedback. From revision. But first, you need something to revise. So ship it. Publish it. Launch it. Share it. Even if it's not ready. Even if it's embarrassing. Even if people judge. At least you tried. At least you created. At least you put something out into the world. That's more than most people do. Be proud of that. Then make it better. But first, finish." },
  { text: "Your potential is limitless. The only limits that exist are the ones you believe. You can learn anything. Become anything. Achieve anything. It might not be easy. It might take time. It might require sacrifice. But it's possible. Humans have done incredible things. Climbed mountains. Cured diseases. Wrote symphonies. Went to space. You are a human too. You have the same potential. The only difference is belief. Do you believe you can? If not, that's the first thing to change. Not your circumstances. Not your resources. Your belief. Change what you believe is possible. Then prove yourself right." },
  { text: "Small daily improvements add up. You don't need to overhaul your life overnight. That's not sustainable. You'll burn out and give up. Instead, focus on getting 1% better every day. Read one page. Do one pushup. Save one dollar. Write one sentence. These tiny actions seem insignificant. But compound interest is the most powerful force in the universe. Small actions, repeated consistently, create massive results. In one year, you'll be 37 times better. In five years, you won't recognize your old self. Start small. Stay consistent. Trust the process. The results will come." },
  { text: "You are stronger than you think. You've survived every hard day so far. Every single one. The breakups. The failures. The losses. The disappointments. You're still here. Still standing. Still fighting. That's not weakness. That's incredible strength. You don't give yourself enough credit. You've overcome so much. You've grown so much. You've become so much. And you'll keep growing. Keep overcoming. Keep becoming. Because that's who you are. A survivor. A fighter. A winner. You just forgot for a moment. Remember now. You are stronger than you think. Prove it again today." },
  { text: "Your excuses are lies you tell yourself. 'I don't have time.' You have the same 24 hours as everyone else. 'I don't have money.' People with nothing have built empires. 'I'm too old.' Colonel Sanders started KFC at 65. 'I'm too young.' Mozart was composing at 5. Excuses protect you from the possibility of failure. But they also protect you from success. Drop the excuses. They're not helping you. They're holding you back. Take responsibility. Take action. Take control. You have everything you need to start. The only thing missing is your willingness to try. Stop lying to yourself. Start doing." },
  { text: "What would you do if you knew you couldn't fail? Answer that question honestly. Then go do that thing. Fear of failure is the only thing stopping you. Not lack of talent. Not lack of resources. Not lack of time. Fear. Fear of looking stupid. Fear of wasting time. Fear of being judged. But what if you couldn't fail? What would you attempt? That's your true desire. That's your calling. Don't let fear steal it from you. Failure is not fatal. It's feedback. It's learning. It's growing. Everyone fails. The only people who never fail are the ones who never try. Don't be that person. Try anyway. Fail anyway. Grow anyway." },
  { text: "Your mindset determines your reality. Two people can have the exact same circumstances and completely different experiences. One sees problems. The other sees opportunities. One sees obstacles. The other sees challenges. One sees failure. The other sees learning. The difference is mindset. You can't always control what happens to you. But you can always control how you respond. How you interpret. What you believe. Choose a growth mindset. Choose to see the good. Choose to believe you can figure it out. Your mindset is a choice. Choose wisely. It shapes everything." },
  { text: "Action cures fear. You can't think your way out of fear. You can't analyze your way out. You can't wait until you're no longer afraid. That day never comes. The only way to overcome fear is to act. To do the thing you're afraid of. To take the first step despite the fear. Action is the antidote. Every time you act despite fear, you prove to yourself that you're capable. You build courage. You build confidence. The fear doesn't disappear. It shrinks. It becomes manageable. So don't wait. Don't overthink. Don't prepare. Act. Take one small step. Feel the fear. Do it anyway. That's courage." },
  { text: "Your network is your net worth. The people you surround yourself with matter. They influence your thoughts. Your habits. Your standards. Your beliefs. If you want to level up, level up your circle. Find people who inspire you. Who challenge you. Who believe in you. Join communities. Attend events. Reach out to mentors. Your network will open doors you can't open alone. Will introduce you to opportunities you didn't know existed. Will support you when times get hard. Invest in relationships. Give more than you take. Your future success depends on the people you know. Choose them carefully." },
  { text: "Rest is productive. Burnout is not a badge of honor. Working yourself into exhaustion is not strength. It's self-destruction. Your body needs rest. Your mind needs rest. Your soul needs rest. You can't perform at your best if you're running on empty. Rest is not laziness. It's maintenance. Like changing the oil in a car. Like sleeping to consolidate memories. Like taking a break to avoid breaking down. Schedule rest. Protect your sleep. Take days off. Listen to your body. The most successful people prioritize recovery. They know that rest is when growth happens. Work hard. Rest hard. That's sustainable success." },
  { text: "Your comfort zone is not safe. It feels safe. But it's actually the most dangerous place you can be. Because nothing grows there. Nothing changes. Nothing improves. You stay stuck while the world moves forward. Comfort is a trap. A seductive trap that promises safety but delivers stagnation. The real safety is in growth. In adaptability. In becoming someone who can handle anything. That only happens outside your comfort zone. So get uncomfortable. Do things that scare you. Take risks. Make mistakes. Grow. Your future self will thank you for leaving safety behind." },
  { text: "You can learn anything. The internet has made knowledge free and accessible. Whatever you want to learn, you can find resources. YouTube tutorials. Online courses. Free articles. Podcasts. Books. There's no excuse for ignorance anymore. The information is out there. You just need curiosity and discipline. Spend 30 minutes a day learning. Read. Watch. Listen. Practice. In one year, you'll be an expert. In five years, you'll be world-class. The time will pass anyway. You can either learn or stay the same. Choose learning. Invest in yourself. It's the best investment you'll ever make." },
  { text: "Your habits shape your future. You are the sum of your habits. What you do every day matters more than what you do once in a while. Small choices compound. The decision to exercise or not. To read or scroll. To save or spend. To work or procrastinate. Each choice seems insignificant. But repeated over time, they define your life. Take control of your habits. Start small. Make it easy. Track your progress. Don't break the chain. Good habits are hard to start but easy to maintain. Bad habits are easy to start but hard to break. Choose your habits carefully. They're building your future." },
  { text: "Your attitude determines your altitude. You can't control what happens to you. But you can control how you respond. Two people face the same setback. One gives up. One learns and grows. The difference is attitude. Choose a positive attitude. Not because life is easy. Because life is hard. And a positive attitude helps you navigate the hard times. It helps you see opportunities instead of obstacles. Helps you find solutions instead of problems. Helps you keep going when you want to quit. Your attitude is a choice. Choose one that serves you. Every morning. Every challenge. Every day." },
  { text: "Start now. Not tomorrow. Not next week. Not when you're ready. Now. The perfect time doesn't exist. The conditions will never be perfect. You'll never have enough money. Enough time. Enough confidence. Enough certainty. The only thing waiting does is delay your progress. Increase your fear. Multiply your excuses. Start now with what you have. Where you are. Who you know. Imperfect action beats perfect inaction. You can adjust course later. You can learn as you go. You can improve over time. But you can't improve something that doesn't exist. Start now. Your future self is waiting." },
  { text: "You are enough. Right now. As you are. Not when you lose weight. Not when you make more money. Not when you achieve your goals. Now. You are worthy of love. Of success. Of happiness. Of respect. Not because of what you do. Because of who you are. Don't tie your worth to your achievements. That's a losing game. There will always be more to achieve. Always someone ahead. Always something missing. Your worth is inherent. It doesn't change based on your circumstances. You are enough. Believe that. Act from that place. Everything else becomes easier when you know your worth." },
  { text: "Your struggle is your strength. Every challenge you've overcome has made you stronger. Every failure has taught you something. Every difficult moment has built resilience. Don't wish for an easy life. Wish for the strength to handle a difficult one. Your struggles are not punishment. They're preparation. For something bigger. Something harder. Something more meaningful. The strongest people are not those who never struggled. They're those who struggled and kept going. You're becoming stronger every day. Even when it doesn't feel like it. Even when you want to quit. Keep going. Your struggle is shaping your strength." },
  { text: "Small wins create momentum. You don't need a massive breakthrough. You just need a small win. Make your bed. Send that email. Do one pushup. Write one sentence. That small win creates momentum. Momentum creates confidence. Confidence creates more action. More action creates bigger wins. Don't underestimate the power of small. A tiny snowball can become an avalanche. A small spark can become a fire. A single step can start a journey. Start small. Win small. Build momentum. Let the snowball roll. Before you know it, you'll have created something massive. But first, one small win. Go get it." },
  { text: "Your future self is watching. What would they want you to do right now? Would they want you to scroll social media or work on your goal? Would they want you to eat junk food or fuel your body? Would they want you to stay in bed or get after it? Your future self is counting on you. The decisions you make today create the person you become tomorrow. Don't let them down. Make choices your future self will thank you for. Not every choice. But most choices. Be someone your future self is proud of. They're watching. They're waiting. They're hoping you choose wisely. Don't disappoint them." },
  { text: "You miss 100% of the shots you don't take. This is obvious. But worth repeating. Every no brings you closer to a yes. Every rejection is a lesson. Every failure is feedback. The only real failure is not trying. Is staying silent. Is playing small. Is letting fear win. Take the shot. Apply for the job. Ask for the date. Start the business. Share the idea. What's the worst that could happen? You get a no. You learn something. You grow. What's the best that could happen? Everything changes. The risk is worth the reward. Always. Take the shot. Today. Don't let fear make the decision for you." },
  { text: "Your energy introduces you before you speak. People can feel your presence. Your enthusiasm. Your passion. Your confidence. Before you say a word. Show up with positive energy. Smile. Stand tall. Make eye contact. Speak clearly. Your energy is contagious. It affects everyone around you. It affects how people perceive you. How they respond to you. How they treat you. Take control of your energy. Not by pretending. By cultivating genuine enthusiasm. Find something to be excited about. Focus on the positive. Share your light. Your energy is a gift. Share it generously. It will come back to you multiplied." },
  { text: "Clarity comes from action, not thought. You can't think your way to clarity. You can't plan your way to certainty. You can't analyze your way to confidence. Clarity comes from doing. From trying. From failing. From adjusting. From trying again. Action reveals the path. The path is hidden until you take the first step. Then the next step becomes visible. Then the next. You don't need to see the whole staircase. Just the first step. Take it. Clarity will follow. Action creates information. Information creates clarity. Clarity creates confidence. Stop overthinking. Start doing. Clarity is waiting on the other side of action." },
  { text: "Your words have power. Speak kindly to yourself. You wouldn't talk to a friend the way you talk to yourself. The harsh criticism. The negative self-talk. The constant comparison. It's not helpful. It's not motivating. It's damaging. Start paying attention to your inner voice. When you notice negative self-talk, stop. Reframe. Speak to yourself like you'd speak to someone you love. With compassion. With encouragement. With belief. Your words shape your beliefs. Your beliefs shape your actions. Your actions shape your life. Speak life to yourself. You're listening. What you say matters. Say things that help you grow." },
  { text: "Discipline is freedom. Most people think discipline is restrictive. Controlling. Limiting. But true discipline is liberating. When you have discipline, you don't have to negotiate with yourself. You don't have to decide if you'll work out. You just work out. You don't have to decide if you'll work on your goal. You just work. Discipline removes the burden of choice. It creates habits. Habits create automaticity. Automaticity creates freedom. Freedom to focus on what matters. Freedom from decision fatigue. Freedom from guilt. Freedom from regret. Discipline is not punishment. It's the path to freedom. Build discipline. Experience freedom." },
  { text: "Your perspective is everything. Two people can experience the same event and have completely different interpretations. One sees failure. The other sees learning. One sees rejection. The other sees redirection. One sees problems. The other sees challenges. You can't always control what happens. But you can always control how you see it. Choose a perspective that serves you. That empowers you. That moves you forward. Not denial. Not toxic positivity. Just a choice to see the good, the lesson, the opportunity. Your perspective is a lens. You can change the lens anytime. Choose one that makes your life better." },
  { text: "The obstacle is the way. What stands in the way becomes the way. Every obstacle is an opportunity. To learn. To grow. To innovate. To become stronger. Don't try to avoid obstacles. Don't complain about them. Embrace them. They're not blocking your path. They are your path. The mountain is not in your way. It is the way. Climb it. Learn from it. Grow because of it. The most successful people don't succeed despite obstacles. They succeed because of obstacles. Obstacles forced them to get creative. To work harder. To become better. Your obstacle is your opportunity. Embrace it. Use it. Grow from it." },
  { text: "You can't change the past. Regret is useless. Guilt is useless. Wishing things were different is useless. The past is gone. You can't undo what happened. You can't unsay what was said. You can't change what you did. But you can learn. You can grow. You can do better next time. The past is a teacher, not a prison. Learn the lesson. Then let it go. Don't carry yesterday's mistakes into today. You deserve a fresh start. Every morning is a new beginning. A chance to try again. To be better. To do better. The past doesn't define you. What you do now defines you. Start fresh today." },
  { text: "Your potential is undiscovered. You have no idea what you're capable of. None. Because you haven't tried. You haven't pushed. You haven't failed enough. Potential is not what you've already done. It's what you could do if you tried your hardest. If you never gave up. If you believed in yourself. Most people never touch their potential. They stop too soon. They settle for good enough. They let fear win. Don't be most people. Keep pushing. Keep growing. Keep failing. Keep learning. You have no idea how amazing you could become. Neither do I. Let's find out together. Don't stop before the miracle happens." },
  { text: "Your habits are your identity. Every action you take is a vote for the person you want to become. Exercise is a vote for being fit. Reading is a vote for being knowledgeable. Saving is a vote for being financially free. Each small action seems insignificant. But over time, these votes add up. They shape your identity. You become what you repeatedly do. Not what you say you'll do. Not what you intend to do. What you actually do. Every day. Without exception. So vote wisely. Cast your vote for the person you want to become. With every small action. Every single day. Your identity is being built right now." },
  { text: "Your focus determines your reality. What you focus on grows. Focus on problems, problems grow. Focus on solutions, solutions grow. Focus on fear, fear grows. Focus on courage, courage grows. Focus on lack, lack grows. Focus on abundance, abundance grows. You get more of what you pay attention to. Not because of magic. Because attention directs action. Action creates results. Choose your focus carefully. What you focus on is what you'll see. What you see is what you'll pursue. What you pursue is what you'll achieve. Focus on what matters. Ignore the rest. Your focus is your most powerful tool. Use it wisely." },
  { text: "Your story is not over. No matter what chapter you're in. The breakup chapter. The job loss chapter. The health crisis chapter. The struggling chapter. It's just a chapter. Not the whole book. The story continues. New chapters are being written. Better chapters are coming. But you have to keep turning the page. Keep living. Keep trying. Keep hoping. The darkest hour is just before dawn. The hardest struggles produce the strongest people. The deepest valleys lead to the highest mountains. Your story is not over. The best chapters might still be ahead. Don't close the book before the good part. Keep reading. Keep writing. Keep going." },
  { text: "Your time is now. Not someday. Not when you're ready. Not when conditions are perfect. Now. Today. This moment. The only moment you have any control over is this one. The past is gone. The future is not guaranteed. All you have is now. Don't waste it waiting. Don't waste it preparing. Don't waste it fearing. Use it. Act now. Start now. Change now. Whatever you've been waiting for, stop waiting. Whatever you've been putting off, start now. Whatever dream you've been holding, pursue it now. Your time is now. Not because conditions are perfect. Because now is all you have. Make it count." },
  { text: "You are not too old. Colonel Sanders started KFC at 65. Vera Wang became a designer at 40. Stan Lee created Marvel at 39. Harrison Ford was a carpenter until his 30s. Age is not an excuse. It's not a limitation. It's not a deadline. You can start anything at any age. Learn any skill. Pursue any dream. Build any life. The only person who cares about your age is you. No one else is paying attention. They're too busy with their own lives. Don't let an arbitrary number stop you from living. You have time. You have potential. You have everything you need. Start now. Age is just a number. You define what's possible." },
  { text: "Your comfort zone is calling. It's whispering sweet lies. Stay here. It's safe. It's easy. Don't risk anything. Don't change anything. Don't grow. But you know the truth. Comfort is a trap. It feels good in the moment. But it leads to stagnation. To regret. To wondering what if. The magic happens outside your comfort zone. The growth. The learning. The breakthroughs. The life you want is out there. Not in here. So step out. Just one step. Do one thing that scares you. Then another. Then another. Your comfort zone will shrink. Your courage will grow. Your life will expand. Take the first step today." },
  { text: "Your self-discipline is like a muscle. It gets stronger with use. Every time you do something you don't feel like doing, you strengthen your discipline. Every time you resist temptation, you strengthen your discipline. Every time you choose long-term benefit over short-term pleasure, you strengthen your discipline. Start small. Make your bed. Do one pushup. Read one page. Write one sentence. Small wins build momentum. Momentum builds confidence. Confidence builds discipline. You're not born disciplined. You build it. One choice at a time. One day at a time. Start building today. Your future self needs a strong discipline muscle. Start exercising it now." },
  { text: "You can't control the waves. But you can learn to surf. Life will always have challenges. Problems. Difficulties. That's not going to change. What can change is your ability to handle them. To navigate them. To thrive despite them. You can't control what happens to you. But you can control your response. Your preparation. Your resilience. You can learn to surf. To ride the waves instead of being crushed by them. To use the energy of the challenge to propel you forward. Don't waste energy trying to control the uncontrollable. Focus on what you can control. Your skills. Your mindset. Your response. Learn to surf. The waves are coming anyway." },
  { text: "Your mindset is your greatest asset or your biggest obstacle. It's a choice. Every day. Every challenge. Every moment. You can choose a growth mindset. I can learn. I can improve. I can figure this out. Or a fixed mindset. I can't. I'm not good at this. This is just who I am. One mindset leads to growth. The other leads to stagnation. Choose wisely. Not once. Every day. Every challenge. Every moment. Catch yourself when you slip into fixed mindset thinking. Reframe. Replace. Choose growth. Your mindset is a choice. Choose one that serves you. Your future depends on it. Literally. Your mindset shapes your reality." },
  { text: "Your passion is not something you find. It's something you build. People say 'follow your passion' as if it's hidden somewhere waiting to be discovered. That's not how it works. Passion comes from mastery. From becoming good at something. From seeing progress. From creating value. You don't find passion. You build it. Choose something interesting. Work hard at it. Get better. See results. Passion will follow. Don't wait to find your passion. Start building it. Today. With whatever you have. Wherever you are. Passion is not the starting line. It's the finish line. Start the race. Passion will meet you there." },
  { text: "Your habits are your destiny. What you do every day matters more than what you do once in a while. Small choices compound. Over time, they become your identity. Your identity becomes your destiny. If you want to change your life, change your habits. Not everything at once. One habit at a time. Start small. Make it easy. Be consistent. Stack habits. Track progress. Don't break the chain. Good habits are hard to start but easy to maintain. Bad habits are easy to start but hard to break. Choose your habits carefully. They're building your future. One day at a time. One habit at a time. Your destiny is being shaped right now." },
  { text: "You are not your failures. You are not your mistakes. You are not the worst thing you've ever done. You are someone who tried and failed. Who learned and grew. Who got back up. Your failures don't define you. Your response to failure defines you. Everyone fails. Everyone makes mistakes. Everyone has regrets. The difference is what you do next. Do you give up? Or do you learn and grow? Do you let failure define you? Or do you define failure? Choose growth. Choose learning. Choose to get back up. Your failures are not your identity. They're just feedback. Learn the lesson. Then let it go. Try again. Do better." },
  { text: "Your dreams are valid. Don't let anyone tell you otherwise. Not your parents. Not your friends. Not society. Not the voice in your head. Your dreams are yours. They came from somewhere. From your unique experiences. Your unique talents. Your unique perspective. Don't abandon them because someone else doesn't understand. Don't shrink your dreams to fit someone else's expectations. Your dreams might seem impossible. Too big. Too crazy. Too unrealistic. So what? Impossible just means it hasn't been done yet. Crazy just means it's different. Unrealistic just means it's ambitious. Your dreams are valid. Protect them. Pursue them. Prove everyone wrong. Start today." },
  { text: "Your energy is contagious. Are you spreading positivity or negativity? Enthusiasm or apathy? Hope or despair? Your energy affects everyone around you. Your team. Your family. Your friends. Your customers. It affects how people feel. How they perform. How they treat others. Take responsibility for your energy. Not by pretending. By genuinely cultivating a positive state. Find things to be grateful for. Find reasons to be excited. Find opportunities to encourage others. Your energy is a gift. Share it generously. It will come back to you multiplied. The energy you put out is the energy you get back. Choose positive energy. Spread it everywhere you go." },
  { text: "Your excuses are lies. 'I don't have time.' You have the same 24 hours as everyone else. 'I don't have money.' People with nothing have built empires. 'I'm not smart enough.' Intelligence is developed, not fixed. 'It's too late.' People have started over at every age. Excuses protect your ego. They let you off the hook. They keep you safe from the possibility of failure. But they also keep you from success. Drop the excuses. Take responsibility. Take action. You have everything you need to start. The only thing missing is your willingness to try. Stop lying to yourself. Start doing. Your excuses are not protecting you. They're holding you back." }
];

app.post('/api/generate-script', async (req, res) => {
  const { topic } = req.body;
  
  if (!topic) {
    return res.status(400).json({ error: 'Topic is required' });
  }

  // Pick random script from library
  const randomIndex = Math.floor(Math.random() * scriptLibrary.length);
  const baseScript = scriptLibrary[randomIndex].text;
  
  // Generate unique titles using AI based on the topic and script
  let titles = { titleA: "", titleB: "", titleC: "" };
  let description = "";
  let hashtags = [];
  
  try {
    const titlePrompt = `Generate 3 unique, clickbait YouTube titles about "${topic}". Make each title different style. No patterns like "The ___ Secret". Be creative. Return ONLY JSON: {"titleA":"title1","titleB":"title2","titleC":"title3"}`;
    
    const titleCompletion = await groq.chat.completions.create({
      messages: [{ role: "user", content: titlePrompt }],
      model: "llama3-70b-8192",
      temperature: 0.95,
      max_tokens: 300,
    });
    
    let titleText = titleCompletion.choices[0]?.message?.content || "";
    titleText = titleText.replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');
    const titleMatch = titleText.match(/\{[\s\S]*\}/);
    if (titleMatch) {
      titles = JSON.parse(titleMatch[0]);
    } else {
      titles = { titleA: `Why I Cared About ${topic}`, titleB: `The ${topic} Moment That Changed Me`, titleC: `Stop Ignoring Your ${topic}` };
    }
    
    const descPrompt = `Write a 2-line YouTube description about "${topic}" with emojis (🔥, 👇, ✅). Make people curious. Return ONLY the description text, no JSON.`;
    const descCompletion = await groq.chat.completions.create({
      messages: [{ role: "user", content: descPrompt }],
      model: "llama3-70b-8192",
      temperature: 0.9,
      max_tokens: 150,
    });
    description = descCompletion.choices[0]?.message?.content || `This hit different. 🔥 Watch until the end. 👇 Subscribe for more.`;
    
    hashtags = [`#${topic.replace(/ /g, '')}`, "#Motivation", "#MindsetShift", "#DailyMotivation", "#Shorts"];
    
  } catch (error) {
    console.error("Title generation error:", error.message);
    titles = { titleA: `Why I Cared About ${topic}`, titleB: `The ${topic} Moment`, titleC: `${topic} Changed My Life` };
    description = `This hit different. 🔥 Watch. 👇 Subscribe.`;
    hashtags = [`#${topic.replace(/ /g, '')}`, "#Motivation", "#Shorts"];
  }

  const wordCount = baseScript.split(/\s+/).length;

  res.json({
    success: true,
    script: baseScript,
    titleA: titles.titleA,
    titleB: titles.titleB,
    titleC: titles.titleC,
    description: description,
    hashtags: hashtags,
    wordCount: wordCount,
    secondsEstimate: Math.round(wordCount / 2.5)
  });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
  console.log(`Loaded ${scriptLibrary.length} scripts`);
});
